-- AlterTable
ALTER TABLE `ActivityLog` MODIFY `action` ENUM('TRANSLATE_ARTICLE', 'CREATE_ARTICLE', 'UPDATE_ARTICLE', 'DELETE_ARTICLE', 'CREATE_EDITION', 'CREATE_EVENT', 'REVIEW_TRANSLATION', 'CREATE_CAROUSEL', 'DELETE_CAROUSEL') NOT NULL;
