-- AlterTable
ALTER TABLE `ActivityLog` MODIFY `action` ENUM('TRANSLATE_ARTICLE', 'CREATE_ARTICLE', 'UPDATE_ARTICLE', 'DELETE_ARTICLE', 'CREATE_EDITION', 'CREATE_EVENT', 'REVIEW_TRANSLATION', 'CREATE_CAROUSEL') NOT NULL;

-- AddForeignKey
ALTER TABLE `ActivityLog` ADD CONSTRAINT `ActivityLog_carouselId_fkey` FOREIGN KEY (`carouselId`) REFERENCES `Carousel`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
